version: '3.7'

services:
  # Postgresql 12.3
  postgres_db:
    image: postgres:12.3
    container_name: postgre-12.3-server01
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  
  # Redis
  redis_db:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
